draw_config:
  key_w: 60
  key_h: 56
  split_gap: 30.0
  combo_w: 28
  combo_h: 26
  key_rx: 6.0
  key_ry: 6.0
  dark_mode: auto
  n_columns: 2
  separate_combo_diagrams: false
  combo_diagrams_scale: 2
  inner_pad_w: 2.0
  inner_pad_h: 2.0
  outer_pad_w: 30.0
  outer_pad_h: 56.0
  line_spacing: 1.2
  arc_radius: 6.0
  append_colon_to_layer_header: true
  small_pad: 2.0
  legend_rel_x: 0.0
  legend_rel_y: 0.0
  draw_key_sides: false
  key_side_pars:
    rel_x: 0.0
    rel_y: 4.0
    rel_w: 12.0
    rel_h: 12.0
    rx: 4.0
    ry: 4.0
  svg_extra_style: ''
  footer_text: Created with <a href="https://github.com/caksoylar/keymap-drawer">keymap-drawer</a>
  shrink_wide_legends: 7
  style_layer_activators: true
  glyph_tap_size: 14
  glyph_hold_size: 12
  glyph_shifted_size: 10
  glyphs: {}
parse_config:
  preprocess: true
  skip_binding_parsing: false
  raw_binding_map: 
    'DE_UDIA': 'Ü'
    'DE_ODIA': 'Ö'
    'DE_ADIA': 'Ä'
    '&uc SUB_0 0': '_₀'
    '&uc SUB_1 0': '_₁'
    '&uc SUB_2 0': '_₂'
    '&uc SUB_3 0': '_₃'
    '&uc SUB_4 0': '_₄'
    '&uc SUB_5 0': '_₅'
    '&uc SUB_6 0': '_₆'
    '&uc SUB_7 0': '_₇'
    '&uc SUB_8 0': '_₈'
    '&uc SUB_9 0': '_₉'
    '&uc SUP_0 0': '_⁰'
    '&uc SUP_1 0': '_¹'
    '&uc SUP_2 0': '_²'
    '&uc SUP_3 0': '_³'
    '&uc SUP_4 0': '_⁴'
    '&uc SUP_5 0': '_⁵'
    '&uc SUP_6 0': '_⁶'
    '&uc SUP_7 0': '_⁷'
    '&uc SUP_8 0': '_⁸'
    '&uc SUP_9 0': '_⁹'
    '&uc UP(0x3BE, 0x3BE)'  : 'ξ'
    '&uc UP(0x3BB, 0x3BB)': 'λ'
    '&uc UP(0x3C7, 0x3C7)': 'χ'
    '&uc UP(0x3C9, 0x3C9)': 'ω'
    '&uc UP(0x3B9, 0x3B9)': 'ι'
    '&uc UP(0x3B1, 0x3B1)': 'α'
    '&uc UP(0x3B5, 0x3B5)': 'ε'
    '&uc UP(0x3BF, 0x3BF)': 'ο'
    '&uc UP(0x3B7, 0x3B7)': 'η'
    '&uc UP(0x3C0, 0x3C0)': 'π'
    '&uc UP(0x3B6, 0x3B6)': 'ζ'
    '&uc UP(0x3BA, 0x3BA)': 'κ'
    '&uc UP(0x3C8, 0x3C8)': 'ψ'
    '&uc UP(0x3B3, 0x3B3)': 'γ'
    '&uc UP(0x3C6, 0x3C6)': 'φ'
    '&uc UP(0x3D5, 0)': 'ϕ'
    '&uc UP(0x3C2, 0)': 'ς'
    '&uc UP(0x3C3, 0x3C3)': 'σ'
    '&uc UP(0x3BD, 0x3BD)': 'ν'
    '&uc UP(0x3C1, 0x3C1)': 'ρ'
    '&uc UP(0x3C4, 0x3C4)': 'τ'
    '&uc UP(0x3B4, 0x3B4)': 'δ'
    '&uc UP(0x3C5, 0x3C5)': 'υ'
    '&uc UP(0x3B2, 0x3B2)': 'β'
    '&uc UP(0x3BC, 0x3BC)': 'μ'
    '&uc UP(0x3F1, 0)': 'ρ'
    '&uc UP(0x3B8, 0x3B8)': 'θ'
    '&uc UP(0x3D1, 0x3D1)': 'ϑ'
  sticky_label: sticky
  toggle_label: toggle
  tap_toggle_label: tap-toggle
  trans_legend:
    t: ▽
    type: trans
  layer_legend_map: {}
  mark_alternate_layer_activators: false
  modifier_fn_map:
    left_ctrl: Ctl
    right_ctrl: Ctl
    left_shift: Sft
    right_shift: Sft
    left_alt: Alt
    right_alt: AltGr
    left_gui: Gui
    right_gui: Gui
    keycode_combiner: '{mods}+{key}'
    mod_combiner: '{mod_1}+{mod_2}'
    special_combinations:
      left_ctrl+left_alt+left_gui+left_shift: Hyper
      left_ctrl+left_alt+left_shift: Meh
  qmk_remove_keycode_prefix:
  - KC_
  qmk_keycode_map:
    XXXXXXX: ''
    'NO': ''
    MINUS: '-'
    MINS: '-'
    EQUAL: '='
    EQL: '='
    LEFT_BRACKET: '['
    LBRC: '['
    RIGHT_BRACKET: ']'
    RBRC: ']'
    BACKSLASH: \
    BSLS: \
    NONUS_HASH: '#'
    NUHS: '#'
    SEMICOLON: ;
    SCLN: ;
    QUOTE: ''''
    QUOT: ''''
    GRAVE: '`'
    GRV: '`'
    COMMA: ','
    COMM: ','
    DOT: .
    SLASH: /
    SLSH: /
    TILDE: '~'
    TILD: '~'
    EXCLAIM: '!'
    EXLM: '!'
    AT: '@'
    HASH: '#'
    DOLLAR: $
    DLR: $
    PERCENT: '%'
    PERC: '%'
    CIRCUMFLEX: ^
    CIRC: ^
    AMPERSAND: '&'
    AMPR: '&'
    ASTERISK: '*'
    ASTR: '*'
    LEFT_PAREN: (
    LPRN: (
    RIGHT_PAREN: )
    RPRN: )
    UNDERSCORE: _
    UNDS: _
    PLUS: +
    LEFT_CURLY_BRACE: '{'
    LCBR: '{'
    RIGHT_CURLY_BRACE: '}'
    RCBR: '}'
    PIPE: '|'
    COLON: ':'
    COLN: ':'
    DOUBLE_QUOTE: '"'
    DQUO: '"'
    DQT: '"'
    LEFT_ANGLE_BRACKET: <
    LABK: <
    LT: <
    RIGHT_ANGLE_BRACKET: '>'
    RABK: '>'
    GT: '>'
    QUESTION: '?'
    QUES: '?'
  zmk_remove_keycode_prefix: []
  zmk_keycode_map:
    EXCLAMATION: '!'
    EXCL: '!'
    AT_SIGN: '@'
    AT: '@'
    HASH: '#'
    POUND: '#'
    DOLLAR: $
    DLLR: $
    PERCENT: '%'
    PRCNT: '%'
    CARET: ^
    AMPERSAND: '&'
    AMPS: '&'
    ASTERISK: '*'
    ASTRK: '*'
    STAR: '*'
    LEFT_PARENTHESIS: (
    LPAR: (
    RIGHT_PARENTHESIS: )
    RPAR: )
    EQUAL: '='
    PLUS: +
    MINUS: '-'
    UNDERSCORE: _
    UNDER: _
    SLASH: /
    FSLH: /
    QUESTION: '?'
    QMARK: '?'
    BACKSLASH: \
    BSLH: \
    PIPE: '|'
    NON_US_BACKSLASH: \
    PIPE2: '|'
    NON_US_BSLH: '|'
    SEMICOLON: ;
    SEMI: ;
    COLON: ':'
    SINGLE_QUOTE: ''''
    SQT: ''''
    APOSTROPHE: ''''
    APOS: ''''
    DOUBLE_QUOTES: '"'
    DQT: '"'
    COMMA: ','
    LESS_THAN: <
    LT: <
    PERIOD: .
    DOT: .
    GREATER_THAN: '>'
    GT: '>'
    LEFT_BRACKET: '['
    LBKT: '['
    LEFT_BRACE: '{'
    LBRC: '{'
    RIGHT_BRACKET: ']'
    RBKT: ']'
    RIGHT_BRACE: '}'
    RBRC: '}'
    GRAVE: '`'
    TILDE: '~'
    NON_US_HASH: '#'
    NUHS: '#'
    TILDE2: '~'
  zmk_combos: {}
  zmk_preamble: '#define KEYMAP_DRAWER'
  zmk_additional_includes: []
